# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart Build web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: The flutter action needs java so include it
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: flutter doctor
      run: flutter doctor -v
        
    - name: clean
      run: flutter clean

    - name: Download Dependencies
      run: flutter pub get

    - name: Build
      #run: flutter build web
      run: flutter build web --release

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #       github_token: ${{ secrets.API_TOKEN_GITHUB }}
    #       publish_dir: ./build/web
    #       force_orphan: true
    #       user_name: 'github-ci[bot]'
    #       user_email: 'github-actions[bot]@users.noreply.github.com'
    #       commit_message: 'Publish to gh-pages'


    - name: Push Publish To Other Git repo
      if: success()
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  
      with:
        source-directory: '/build/web'
        destination-github-username: 'akaravi'
        destination-repository-name: 'ntk_flutter_estate.Publish'
        user-email: karavi.alireza@gmail.com
        #destination-repository-username :
        commit-message: See $GITHUB_REF
        target-branch: main
  
    - name: Webhook Sms
      uses: joelwmale/webhook-action@master
      with:
        url: 'https://smsban.com/api/?action=SMS_SEND&username=${{ vars.SMS_USERNAME }}&password=${{ secrets.SMS_PASSWORD }}&api=${{ vars.SMS_API }}&from=${{ vars.SMS_FROM }}&API_CHANGE_ALLOW=true&to=${{ vars.SMS_TO }}&text=${{ github.repository }} status is ${{ job.status }}'
        #headers: '{"repository": "joelwmale/webhook-action"}'
        #body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'
    - name: Webhook Plesk
      uses: joelwmale/webhook-action@master
      with:
        url: '${{vars.PLESK_WEBHOOK_ALONAK_APP}}'
  
    - name: Test get variable exported by push-to-another-repository
      run: echo $DESTINATION_CLONED_DIRECTORY
  